-- Geração de Modelo físico
-- Sql ANSI 2003 - brModelo.



CREATE TABLE STATUS_MATRICULA (
NOME VARCHAR(100),
ID_STATUS_MATRICULA INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY
)

CREATE TABLE IMAGENS (
ID_IMAGEM INTEGER PRIMARY KEY,
NOME_IMAGEM VARCHAR(400)
)

CREATE TABLE ADMIN (
id_user INTEGER,
ACESSO INTEGER
)

CREATE TABLE POST_IMAGENS (
ID_POST INTEGER,
ID_IMAGEM INTEGER,
ID_IMAGEM_POST VARCHAR(10) PRIMARY KEY,
FOREIGN KEY(ID_IMAGEM) REFERENCES IMAGENS (ID_IMAGEM) ON UPDATE CASCADE ON DELETE CASCADE
)

CREATE TABLE USERS (
id_user INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
name VARCHAR(200),
password VARCHAR(255),
email VARCHAR(200),
email_veried_at VARCHAR(10),
remember_token VARCHAR(10),
created_at VARCHAR(100),
updated_at VARCHAR(100)
)

CREATE TABLE PACOTES (
ID_PACOTE INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
NOME_PACOTE VARCHAR(200),
ID_CATEGORIA INTEGER,
DESCRICAO VARCHAR(200),
DURACAO VARCHAR(50),
STATUS VARCHAR(50),
ORDEM INTEGER
)

CREATE TABLE CURSOS (
ID_CURSO INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
DURACAO VARCHAR(50),
NOME_CURSO VARCHAR(200)
)

CREATE TABLE Cursos_Pacotes (
ID_PACOTES_CURSOS INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
ID_CURSO INTEGER,
ID_PACOTE INTEGER,
FOREIGN KEY(ID_CURSO) REFERENCES CURSOS (ID_CURSO) ON UPDATE CASCADE ON DELETE RESTRICT,
FOREIGN KEY(ID_PACOTE) REFERENCES PACOTES (ID_PACOTE) ON UPDATE CASCADE ON DELETE RESTRICT
)

CREATE TABLE CURSO_MATRICULA (
ID_MATRICULA INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
ID_PACOTES_CURSOS INTEGER,
ID_STATUS_MATRICULA INTEGER,
FOREIGN KEY(ID_PACOTES_CURSOS) REFERENCES Cursos_Pacotes (ID_PACOTES_CURSOS) ON UPDATE CASCADE ON DELETE RESTRICT,
FOREIGN KEY(ID_STATUS_MATRICULA) REFERENCES STATUS_MATRICULA (ID_STATUS_MATRICULA) ON UPDATE CASCADE ON DELETE RESTRICT
)

CREATE TABLE COMMENTS_POST (
ID_POST_COMMENTS INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
ID_COMMENT INTEGER,
ID_POST INTEGER,
STATUS INTEGER
)

CREATE TABLE COMMENTS (
ID_COMMENT INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
CONTEUDO VARCHAR(900)
)

CREATE TABLE CATEGORIAS (
ID_CATEGORIA INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
NOME_CATEGORIA VARCHAR(200),
ORDEM INTEGER
)

CREATE TABLE POST (
ID_POST INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
CONTEUDO VARCHAR(400),
ID_CATEGORIA INTEGER,
FOREIGN KEY(ID_CATEGORIA) REFERENCES CATEGORIAS (ID_CATEGORIA) ON UPDATE CASCADE ON DELETE RESTRICT
)

CREATE TABLE ALUNO (
id_user INTEGER,
SOBRENOME VARCHAR(200),
CPF CHAR(14),
RG VARCHAR(12),
NASCIMENTO DATETIME,
HISTORICO VARCHAR(200),
FOREIGN KEY(id_user) REFERENCES USERS (id_user) ON UPDATE CASCADE ON DELETE CASCADE
)

ALTER TABLE ADMIN ADD FOREIGN KEY(id_user) REFERENCES USERS (id_user) ON UPDATE CASCADE ON DELETE CASCADE
ALTER TABLE POST_IMAGENS ADD FOREIGN KEY(ID_POST) REFERENCES POST (ID_POST) ON UPDATE CASCADE ON DELETE CASCADE
ALTER TABLE PACOTES ADD FOREIGN KEY(ID_CATEGORIA) REFERENCES CATEGORIAS (ID_CATEGORIA) ON UPDATE CASCADE ON DELETE RESTRICT
ALTER TABLE COMMENTS_POST ADD FOREIGN KEY(ID_COMMENT) REFERENCES COMMENTS (ID_COMMENT) ON UPDATE CASCADE ON DELETE CASCADE
ALTER TABLE COMMENTS_POST ADD FOREIGN KEY(ID_POST) REFERENCES POST (ID_POST) ON UPDATE CASCADE ON DELETE CASCADE
